# Generated by Django 3.2.6 on 2021-09-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communitypost_market_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
