# Generated by Django 3.2.6 on 2021-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorpost',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
